#ifndef MENU_HEADER_H_INCLUDED
#define MENU_HEADER_H_INCLUDED

#define MY_MENU_ID 1
#define MY_FILE_EXIT_ID 0
#define MY_LINE_DIRECT_ID 2
#define MY_LINE_DDA_ID 3
#define MY_LINE_MIDPOINT_ID 4
#define MY_DirectCircle_MENU_ID 6
#define MY_MIDPOINTCIRCLE_MENU_ID 5
#define MY_POLARCIRCLE_MENU_ID 9
#define MY_CLIP_LINE_MENU_ID 7
#define MY_CLIP_POLYGON_MENU_ID 12
#define MY_FLOOD_FILLING_MENU_ID 8
#define MY_BEZIER_MENU_ID 10
#define MY_HERMIT_MENU_ID 11
#define MY_SAVE_MENU_ID 12
#define MY_LOAD_MENU_ID 13
#define MY_POLYGON_MENU_ID 14

#endif // MENU_HEADER_H_INCLUDED
